# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.org.notification=INFO
logging.level.org.springframework=INFO

# Server port (optional)
server.port=8082

# Firebase service account file path (to be mounted via Docker/Kubernetes)
firebase.service.account.path=/app/inji-sender-dtp-meu-imovel-rural-487c8e5dc36a.json

#Audit properties
audit.enabled=${AUDIT_ENABLED:false}
