# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.org.notification=INFO
logging.level.org.springframework=INFO

# Server port (optional)
server.port=8082

#Audit properties
audit.enabled=${AUDIT_ENABLED:false}


# WSO2 OAuth2 token
wso2.token.url=${WSO2_TOKEN_URL}
wso2.token.client-id=${WSO2_CLIENT_ID}
wso2.token.client-secret=${WSO2_CLIENT_SECRET}

# WSO2 MIR API
wso2.mir.base-url=${WSO2_MIR_BASE_URL}
wso2.mir.notification-path=${WSO2_MIR_NOTIFICATION_PATH}
